// ============================================
// Stage 1 Agent: PDF Extraction & Structured Conversion
// ============================================

import { callClaudeForJson } from '../services/claude-client';
import { parsePdf } from '../services/pdf-parser';
import { renderPrompt } from '../prompts/prompt-renderer';
import { createLogger } from '../utils/logger';
import { wrapError } from '../utils/error-handler';
import { measureTime } from '../utils/helpers';
import { ExtractionResult } from './types';
import * as path from 'path';

const logger = createLogger();

export interface Stage1Input {
  workflowId: string;
  pdfFilePath: string;
  clientName: string;
  expectedRecordCount?: number;
}

export interface Stage1Output {
  result: ExtractionResult;
  tokenUsage: number;
  processingTimeMs: number;
}

/**
 * Execute Stage 1: Extract rate card data from a PDF file
 */
export async function executeStage1(input: Stage1Input): Promise<Stage1Output> {
  logger.stageStart(1, 'Extract');

  try {
    let pdfText: string;

    // In mock mode, skip actual PDF parsing
    if (process.env.MOCK_MODE === 'true') {
      logger.info('Mock mode: skipping PDF parsing', {
        stage: 1,
        action: 'pdf_parse_skip',
        data: { filePath: input.pdfFilePath },
      });
      pdfText = '[Mock PDF content - rate card data will be generated by mock Claude response]';
    } else {
      // Step 1: Parse PDF to text
      logger.info('Parsing PDF file...', {
        stage: 1,
        action: 'pdf_parse',
        data: { filePath: input.pdfFilePath },
      });

      const pdfResult = await parsePdf(input.pdfFilePath);

      if (!pdfResult.success) {
        throw new Error(`PDF parsing failed: ${pdfResult.error}`);
      }

      if (!pdfResult.text || pdfResult.text.trim().length === 0) {
        throw new Error('PDF contains no extractable text. The file may be image-based (scanned).');
      }

      logger.info(`PDF parsed: ${pdfResult.pageCount} pages, ${pdfResult.text.length} characters`, {
        stage: 1,
        action: 'pdf_parsed',
        data: { pages: pdfResult.pageCount, characters: pdfResult.text.length },
      });

      pdfText = pdfResult.text;
    }

    // Step 2: Build prompt and call Claude
    const rendered = renderPrompt({
      stage: 1,
      context: {
        clientName: input.clientName,
        expectedRecordCount: input.expectedRecordCount,
        pdfText,
      },
    });

    const { result: claudeResult, durationMs } = await measureTime(() =>
      callClaudeForJson<ExtractionResult>({
        systemPrompt: rendered.systemPrompt,
        userPrompt: rendered.userPrompt,
        stageNumber: 1,
        workflowId: input.workflowId,
      })
    );

    const output: Stage1Output = {
      result: claudeResult.parsed,
      tokenUsage: claudeResult.raw.tokenUsage.totalTokens,
      processingTimeMs: durationMs,
    };

    logger.stageComplete(1, 'Extract', durationMs);
    logger.info(`Extraction result: ${claudeResult.parsed.extraction_status}, confidence: ${claudeResult.parsed.confidence_score}`, {
      stage: 1,
      action: 'extraction_complete',
      data: {
        status: claudeResult.parsed.extraction_status,
        confidence: claudeResult.parsed.confidence_score,
        totalRows: claudeResult.parsed.extracted_data?.metadata?.total_rows,
        flags: claudeResult.parsed.flags?.length || 0,
      },
    });

    return output;
  } catch (error) {
    logger.stageFailed(1, 'Extract', (error as Error).message);
    throw wrapError(error, 1, input.workflowId, {
      pdfFile: path.basename(input.pdfFilePath),
      clientName: input.clientName,
    });
  }
}
